config:
  application:
    username:           'jack'
  platform:
    garminconnect:
      username: "jack"
      password: "xyz"
      api_base_url: "http://connect.garmin.com/proxy"
    trainingpeaks:
      client_id: "missing"
      client_secret: "missing"
      client_scope: "cats:cuddle dogs:throw-frisbee"
      api_base_url: "https://api.trainingpeaks.com"
      oauth_base_url: "https://oauth.trainingpeaks.com"